# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gerson Sunyé
email: gerson.sunye@univ-nantes.fr
description: >- # this means to ignore newlines until "baseurl:"
  Université de Nantes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sunye.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sunye
github_username:  sunye

copyright: 'Copyright &copy; 2016 Gerson Sunyé All Rights Reserved.'
credits: 'This site was built using <a href="http://jekyllrb.com">Jekyll</a>, <a href="http://getbootstrap.com">Bootstrap</a> and <a href="https://startbootstrap.com">Startbootstrap</a>.'


# Build settings
markdown: kramdown
theme: minima
#theme: jekyll-theme-slate

plugins:
  - jekyll-feed
  - highlight
  - include

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


social:
  - title: Twitter
    url: https://twitter.com/sunye
  - title: GitHub
    url: https://github.com/sunye
  - title: LinkedIn
    url: https://www.linkedin.com/in/gsunye
  - title: Scholar
    url: https://scholar.google.fr/citations?user=A6rmSUwAAAAJ&hl=en&oi=ao
  - title: Slideshare
    url: http://www.slideshare.net/sunye/
  - title: DBLP
    url: http://dblp.dagstuhl.de/pers/hd/s/Suny=eacute=:Gerson
